// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using lugiaweather_api.Data;

#nullable disable

namespace lugiaweather_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250608044400_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("lugiaweather_api.Models.Alerta", b =>
                {
                    b.Property<long>("IdAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("id_alerta");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdAlerta"));

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("mensagem");

                    b.Property<int>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("tipo");

                    b.HasKey("IdAlerta");

                    b.ToTable("TBL_ALERTA");
                });

            modelBuilder.Entity("lugiaweather_api.Models.DispositivoIot", b =>
                {
                    b.Property<long>("IdDispositivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("id_dispositivo");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdDispositivo"));

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_criacao")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<long>("IdEndereco")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("id_endereco");

                    b.Property<string>("IdModulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("id_modulo");

                    b.Property<string>("MacEndereco")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("mac_endereco");

                    b.Property<string>("Projeto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("projeto");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("status");

                    b.HasKey("IdDispositivo");

                    b.HasIndex("IdEndereco");

                    b.ToTable("TBL_DISPOSITIVO_IOT");
                });

            modelBuilder.Entity("lugiaweather_api.Models.Endereco", b =>
                {
                    b.Property<long>("IdEndereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("id_endereco");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdEndereco"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("bairro");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("complemento");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_criacao")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("NUMERIC(10,6)")
                        .HasColumnName("latitude");

                    b.Property<string>("Localidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("localidade");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("logradouro");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("NUMERIC(11,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("CHAR(2)")
                        .HasColumnName("uf");

                    b.HasKey("IdEndereco");

                    b.ToTable("TBL_ENDERECO");
                });

            modelBuilder.Entity("lugiaweather_api.Models.Leitura", b =>
                {
                    b.Property<long>("IdLeitura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("id_leitura");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdLeitura"));

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_criacao");

                    b.Property<long?>("IdAlerta")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("id_alerta");

                    b.Property<long>("IdDispositivo")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("id_dispositivo");

                    b.Property<decimal>("NivelAguaCm")
                        .HasColumnType("NUMERIC(8,3)")
                        .HasColumnName("nivel_agua_cm");

                    b.Property<int>("StatusNivel")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("status_nivel");

                    b.HasKey("IdLeitura");

                    b.HasIndex("IdAlerta");

                    b.HasIndex("IdDispositivo");

                    b.ToTable("TBL_LEITURA");
                });

            modelBuilder.Entity("lugiaweather_api.Models.DispositivoIot", b =>
                {
                    b.HasOne("lugiaweather_api.Models.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("IdEndereco")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("lugiaweather_api.Models.Leitura", b =>
                {
                    b.HasOne("lugiaweather_api.Models.Alerta", "Alerta")
                        .WithMany()
                        .HasForeignKey("IdAlerta");

                    b.HasOne("lugiaweather_api.Models.DispositivoIot", "Dispositivo")
                        .WithMany()
                        .HasForeignKey("IdDispositivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alerta");

                    b.Navigation("Dispositivo");
                });
#pragma warning restore 612, 618
        }
    }
}
