// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using lugiaweather_api.Data;

#nullable disable

namespace lugiaweather_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("lugiaweather_api.Models.Alerta", b =>
                {
                    b.Property<long>("IdAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_ALERTA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdAlerta"));

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CRIACAO")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("MENSAGEM");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TIPO");

                    b.HasKey("IdAlerta");

                    b.ToTable("TBL_ALERTA");
                });

            modelBuilder.Entity("lugiaweather_api.Models.DispositivoIot", b =>
                {
                    b.Property<long>("IdDispositivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_DISPOSITIVO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdDispositivo"));

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_ATUALIZACAO");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CRIACAO")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<long>("IdEndereco")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_ENDERECO");

                    b.Property<string>("IdModulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("ID_MODULO");

                    b.Property<string>("MacEndereco")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MAC_ENDERECO");

                    b.Property<string>("Projeto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("PROJETO");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("STATUS");

                    b.HasKey("IdDispositivo");

                    b.HasIndex("IdEndereco");

                    b.ToTable("TBL_DISPOSITIVO_IOT");
                });

            modelBuilder.Entity("lugiaweather_api.Models.Endereco", b =>
                {
                    b.Property<long>("IdEndereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_ENDERECO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdEndereco"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("BAIRRO");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("COMPLEMENTO");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_ATUALIZACAO");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CRIACAO")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("NUMERIC(10,6)")
                        .HasColumnName("LATITUDE");

                    b.Property<string>("Localidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("LOCALIDADE");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("LOGRADOURO");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("NUMERIC(11,6)")
                        .HasColumnName("LONGITUDE");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("CHAR(2)")
                        .HasColumnName("UF");

                    b.HasKey("IdEndereco");

                    b.ToTable("TBL_ENDERECO");
                });

            modelBuilder.Entity("lugiaweather_api.Models.Leitura", b =>
                {
                    b.Property<long>("IdLeitura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_LEITURA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdLeitura"));

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CRIACAO")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<long?>("IdAlerta")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_ALERTA");

                    b.Property<long>("IdDispositivo")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_DISPOSITIVO");

                    b.Property<decimal>("NivelAguaCm")
                        .HasColumnType("NUMERIC(8,3)")
                        .HasColumnName("NIVEL_AGUA_CM");

                    b.Property<string>("StatusNivel")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("STATUS_NIVEL");

                    b.HasKey("IdLeitura");

                    b.HasIndex("IdAlerta");

                    b.HasIndex("IdDispositivo");

                    b.ToTable("TBL_LEITURA");
                });

            modelBuilder.Entity("lugiaweather_api.Models.DispositivoIot", b =>
                {
                    b.HasOne("lugiaweather_api.Models.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("IdEndereco")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("lugiaweather_api.Models.Leitura", b =>
                {
                    b.HasOne("lugiaweather_api.Models.Alerta", "Alerta")
                        .WithMany()
                        .HasForeignKey("IdAlerta");

                    b.HasOne("lugiaweather_api.Models.DispositivoIot", "Dispositivo")
                        .WithMany()
                        .HasForeignKey("IdDispositivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alerta");

                    b.Navigation("Dispositivo");
                });
#pragma warning restore 612, 618
        }
    }
}
